apiVersion: v1
kind: Service
metadata:
  name: fastapi-server
  labels: 
    app: fastapi-server
spec:
  selector:
    app: fastapi-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083