apiVersion: v1
kind: Service
metadata:
  name: mongodb-community-server
  labels: 
    app: mongodb-community-server
spec:
  selector:
    app: mongodb-community-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  
