apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
stringData:
  environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongodb-crud-server


      