apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongopvc
  labels:
    app: mongodb-community-server
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi


